# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'svLPMGui.ui'
#
# Created: Fri Aug 11 15:16:41 2017
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1300, 675)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 675))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Resistor = QtGui.QPushButton(self.centralwidget)
        self.Resistor.setGeometry(QtCore.QRect(20, 70, 61, 51))
        self.Resistor.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/Resistor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Resistor.setIcon(icon)
        self.Resistor.setIconSize(QtCore.QSize(45, 50))
        self.Resistor.setObjectName(_fromUtf8("Resistor"))
        self.Capacitor = QtGui.QPushButton(self.centralwidget)
        self.Capacitor.setGeometry(QtCore.QRect(20, 130, 61, 51))
        self.Capacitor.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/capacitor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Capacitor.setIcon(icon1)
        self.Capacitor.setIconSize(QtCore.QSize(50, 50))
        self.Capacitor.setObjectName(_fromUtf8("Capacitor"))
        self.Inductor = QtGui.QPushButton(self.centralwidget)
        self.Inductor.setGeometry(QtCore.QRect(20, 190, 61, 51))
        self.Inductor.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/Inductor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Inductor.setIcon(icon2)
        self.Inductor.setIconSize(QtCore.QSize(45, 45))
        self.Inductor.setObjectName(_fromUtf8("Inductor"))
        self.DCVoltageSource = QtGui.QPushButton(self.centralwidget)
        self.DCVoltageSource.setGeometry(QtCore.QRect(20, 240, 61, 51))
        self.DCVoltageSource.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/DCVoltageSource.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DCVoltageSource.setIcon(icon3)
        self.DCVoltageSource.setIconSize(QtCore.QSize(50, 50))
        self.DCVoltageSource.setObjectName(_fromUtf8("DCVoltageSource"))
        self.Diode = QtGui.QPushButton(self.centralwidget)
        self.Diode.setGeometry(QtCore.QRect(20, 300, 61, 51))
        self.Diode.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/Diode.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Diode.setIcon(icon4)
        self.Diode.setIconSize(QtCore.QSize(45, 60))
        self.Diode.setObjectName(_fromUtf8("Diode"))
        self.CircuitView = QtGui.QGraphicsView(self.centralwidget)
        self.CircuitView.setGeometry(QtCore.QRect(100, 10, 1171, 600))
        self.CircuitView.setStatusTip(_fromUtf8(""))
        self.CircuitView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.CircuitView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.CircuitView.setObjectName(_fromUtf8("CircuitView"))
        self.DeleteWire = QtGui.QPushButton(self.centralwidget)
        self.DeleteWire.setGeometry(QtCore.QRect(0, 460, 101, 31))
        self.DeleteWire.setObjectName(_fromUtf8("DeleteWire"))
        self.BoundaryFace = QtGui.QPushButton(self.centralwidget)
        self.BoundaryFace.setGeometry(QtCore.QRect(20, 350, 61, 51))
        self.BoundaryFace.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/BoundaryFace.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BoundaryFace.setIcon(icon5)
        self.BoundaryFace.setIconSize(QtCore.QSize(30, 35))
        self.BoundaryFace.setObjectName(_fromUtf8("BoundaryFace"))
        self.Ground = QtGui.QPushButton(self.centralwidget)
        self.Ground.setGeometry(QtCore.QRect(20, 400, 61, 51))
        self.Ground.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/Ground.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Ground.setIcon(icon6)
        self.Ground.setIconSize(QtCore.QSize(35, 70))
        self.Ground.setObjectName(_fromUtf8("Ground"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 61, 51))
        self.label.setToolTip(_fromUtf8(""))
        self.label.setStatusTip(_fromUtf8(""))
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/SimVascular.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 500, 101, 31))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/Stanford.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 530, 101, 21))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/Engineering.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 22))
        self.menubar.setAutoFillBackground(True)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSolveLPM = QtGui.QMenu(self.menubar)
        self.menuSolveLPM.setObjectName(_fromUtf8("menuSolveLPM"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionSave_2 = QtGui.QAction(MainWindow)
        self.actionSave_2.setObjectName(_fromUtf8("actionSave_2"))
        self.actionSaveAs = QtGui.QAction(MainWindow)
        self.actionSaveAs.setObjectName(_fromUtf8("actionSaveAs"))
        self.actionQuit_2 = QtGui.QAction(MainWindow)
        self.actionQuit_2.setObjectName(_fromUtf8("actionQuit_2"))
        self.actionSolve_ODEs = QtGui.QAction(MainWindow)
        self.actionSolve_ODEs.setObjectName(_fromUtf8("actionSolve_ODEs"))
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_2)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_2)
        self.menuSolveLPM.addAction(self.actionSolve_ODEs)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSolveLPM.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "SimVascular Lumped Parameter Modeller", None, QtGui.QApplication.UnicodeUTF8))
        self.Resistor.setToolTip(QtGui.QApplication.translate("MainWindow", "Resistor", None, QtGui.QApplication.UnicodeUTF8))
        self.Resistor.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to Create Resistor", None, QtGui.QApplication.UnicodeUTF8))
        self.Capacitor.setToolTip(QtGui.QApplication.translate("MainWindow", "Capacitor", None, QtGui.QApplication.UnicodeUTF8))
        self.Capacitor.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to Create Capacitor", None, QtGui.QApplication.UnicodeUTF8))
        self.Inductor.setToolTip(QtGui.QApplication.translate("MainWindow", "Inductor", None, QtGui.QApplication.UnicodeUTF8))
        self.Inductor.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to Create Inductor", None, QtGui.QApplication.UnicodeUTF8))
        self.DCVoltageSource.setToolTip(QtGui.QApplication.translate("MainWindow", "DC Voltage Source", None, QtGui.QApplication.UnicodeUTF8))
        self.DCVoltageSource.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to Create DC Voltage Source", None, QtGui.QApplication.UnicodeUTF8))
        self.Diode.setToolTip(QtGui.QApplication.translate("MainWindow", "Diode", None, QtGui.QApplication.UnicodeUTF8))
        self.Diode.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to Create Diode", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteWire.setToolTip(QtGui.QApplication.translate("MainWindow", "Delete Last Created Wire", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteWire.setStatusTip(QtGui.QApplication.translate("MainWindow", "Delete Last Created Wire", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteWire.setText(QtGui.QApplication.translate("MainWindow", "Delete Wire", None, QtGui.QApplication.UnicodeUTF8))
        self.BoundaryFace.setToolTip(QtGui.QApplication.translate("MainWindow", "Boundary Face ", None, QtGui.QApplication.UnicodeUTF8))
        self.BoundaryFace.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to Create Boundary Face ", None, QtGui.QApplication.UnicodeUTF8))
        self.Ground.setToolTip(QtGui.QApplication.translate("MainWindow", "Ground Point ", None, QtGui.QApplication.UnicodeUTF8))
        self.Ground.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to Create Ground Point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Developed by Stanford University Marsden Cardiovascular Biomechanics Computation Laboratory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setStatusTip(QtGui.QApplication.translate("MainWindow", "Developed by : S.M. Hsia and K.K. Patel", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File ", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSolveLPM.setTitle(QtGui.QApplication.translate("MainWindow", "Solve LPM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to Clear Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_2.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit_2.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSolve_ODEs.setText(QtGui.QApplication.translate("MainWindow", "Solve ODEs", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
