# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LumpedGui.ui'
#
# Created: Fri Jul 14 15:52:27 2017
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(991, 626)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.ComponentList = QtGui.QToolBox(self.centralwidget)
        self.ComponentList.setGeometry(QtCore.QRect(0, 0, 231, 531))
        self.ComponentList.setMouseTracking(True)
        self.ComponentList.setAcceptDrops(True)
        self.ComponentList.setObjectName(_fromUtf8("ComponentList"))
        self.Components = QtGui.QWidget()
        self.Components.setGeometry(QtCore.QRect(0, 0, 231, 497))
        self.Components.setObjectName(_fromUtf8("Components"))
        self.Resistor = DragButton(self.Components)
        self.Resistor.setGeometry(QtCore.QRect(40, 30, 131, 61))
        self.Resistor.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.Resistor.setAcceptDrops(False)
        self.Resistor.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resistor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Resistor.setIcon(icon)
        self.Resistor.setIconSize(QtCore.QSize(130, 67))
        self.Resistor.setFlat(True)
        self.Resistor.setObjectName(_fromUtf8("Resistor"))
        self.Capacitor = DragButton(self.Components)
        self.Capacitor.setGeometry(QtCore.QRect(80, 120, 51, 51))
        self.Capacitor.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.Capacitor.setAcceptDrops(False)
        self.Capacitor.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("capacitor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Capacitor.setIcon(icon1)
        self.Capacitor.setIconSize(QtCore.QSize(150, 60))
        self.Capacitor.setCheckable(False)
        self.Capacitor.setFlat(True)
        self.Capacitor.setObjectName(_fromUtf8("Capacitor"))
        self.Diode = DragButton(self.Components)
        self.Diode.setGeometry(QtCore.QRect(50, 190, 111, 71))
        self.Diode.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.Diode.setAcceptDrops(False)
        self.Diode.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Diode.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Diode.setIcon(icon2)
        self.Diode.setIconSize(QtCore.QSize(200, 67))
        self.Diode.setFlat(True)
        self.Diode.setObjectName(_fromUtf8("Diode"))
        self.Inductor = DragButton(self.Components)
        self.Inductor.setGeometry(QtCore.QRect(40, 280, 141, 51))
        self.Inductor.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.Inductor.setAcceptDrops(False)
        self.Inductor.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Inductor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Inductor.setIcon(icon3)
        self.Inductor.setIconSize(QtCore.QSize(135, 80))
        self.Inductor.setFlat(True)
        self.Inductor.setObjectName(_fromUtf8("Inductor"))
        self.DCVoltageSource = DragButton(self.Components)
        self.DCVoltageSource.setGeometry(QtCore.QRect(70, 350, 71, 71))
        self.DCVoltageSource.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.DCVoltageSource.setAcceptDrops(False)
        self.DCVoltageSource.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("DCVoltageSource.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DCVoltageSource.setIcon(icon4)
        self.DCVoltageSource.setIconSize(QtCore.QSize(100, 60))
        self.DCVoltageSource.setFlat(True)
        self.DCVoltageSource.setObjectName(_fromUtf8("DCVoltageSource"))
        self.ComponentList.addItem(self.Components, _fromUtf8(""))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(239, -1, 561, 651))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.widget = QtGui.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 581, 581))
        self.widget.setAcceptDrops(True)
        self.widget.setObjectName(_fromUtf8("widget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 991, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpem = QtGui.QAction(MainWindow)
        self.actionOpem.setObjectName(_fromUtf8("actionOpem"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "svLumpedPM", None, QtGui.QApplication.UnicodeUTF8))
        self.Resistor.setToolTip(QtGui.QApplication.translate("MainWindow", "Resistor", None, QtGui.QApplication.UnicodeUTF8))
        self.Resistor.setStatusTip(QtGui.QApplication.translate("MainWindow", "Resistor Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.Capacitor.setToolTip(QtGui.QApplication.translate("MainWindow", "Capacitor", None, QtGui.QApplication.UnicodeUTF8))
        self.Capacitor.setStatusTip(QtGui.QApplication.translate("MainWindow", "Capacitor Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.Diode.setToolTip(QtGui.QApplication.translate("MainWindow", "Diode", None, QtGui.QApplication.UnicodeUTF8))
        self.Diode.setStatusTip(QtGui.QApplication.translate("MainWindow", "Diode Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.Inductor.setToolTip(QtGui.QApplication.translate("MainWindow", "Inductor", None, QtGui.QApplication.UnicodeUTF8))
        self.Inductor.setStatusTip(QtGui.QApplication.translate("MainWindow", "Inductor Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.DCVoltageSource.setToolTip(QtGui.QApplication.translate("MainWindow", "DC Voltage Source", None, QtGui.QApplication.UnicodeUTF8))
        self.DCVoltageSource.setStatusTip(QtGui.QApplication.translate("MainWindow", "DC Voltage Source Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.ComponentList.setItemText(self.ComponentList.indexOf(self.Components), QtGui.QApplication.translate("MainWindow", "Circuit Components", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpem.setText(QtGui.QApplication.translate("MainWindow", "Opem", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))

from dragbutton import DragButton
